### ISSUE TITLE
By what principle does it work?

### ISSUE THREAD

**Issue by whyrmph** [fsalinas26/cpp-login-menu#3]
Hello, what is the principle of authorization and registration

He asks for a license, but how will I get it if there is no user data

what is an api token and a public token in config.json?

**Comment by fsalinas26** [comment]
Hey, thanks for the question!    

Here's how the registration and authentication scheme works.   
1. In order to generate a license, we use [GenerateKey.js](https://github.com/fsalinas26/cpp-login-menu/blob/master/NodeJS%20Server/Commands/GenerateKey.js) from our NodeJS server, which is an admin-only function. You can see how to make this API call [here](https://github.com/fsalinas26/cpp-login-menu/blob/master/NodeJS%20Server/test.rest#)  
2. When a key is generated, an entry is made into the SQLite Database with the license and a NULL Username. Alternatively, you can make two tables in the SQLite Database, one for licenses and one for users (which would be more ideal IMO)
3. When the user registers with this license, the server will check that the license has a NULL Username indicating that it has not yet been redeemed. Once that check is passed, the server updates the table entry and populates the username field along with any other respective variables.   
  
The API token allows access to the admin API calls. You must include this in the header. The public token is for clients to make requests to your server and revoke any unauthorized pings/reqs. Public is for your client-side, API is for admin API access.
